#!/bin/bash

#SBATCH --gres=gpu:1
#SBATCH --job-name=PeftTraining
#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=00:05:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output/test-training-models_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/CoT/
source activate cot

# srun python -u cot/peft_prompt_tuning.py
srun python -u cot/train.py